ABySS  kc calcuation ntCard feature
bcgsc/abyss pull request #370
Opened 2021-05-25 13:00 UTC by jowong4

This pull request contains the automatic kc detection using ntCard.

2021-05-25 16:36 UTC, schutzekatze requested changes

2021-05-25 16:36 UTC, schutzekatze commented on BloomDBG/bloom-dbg.cc
> +		size_t ntCard_histSize = 10002;
What's the magic number `10002`?

2021-05-25 16:36 UTC, schutzekatze commented on BloomDBG/bloom-dbg.cc
> +		float cov = calculateCoverageThreshold(hi);
`const` wherever possible.

2021-06-03 00:15 UTC, schutzekatze approved these changes

2021-08-31 20:58 UTC, jowong4 commented
Threshold determined with ntCard is on most occasions worse than just using the default of kc=2

2021-08-31 20:58 UTC, closed without merging