Sealer: seal lower case iupac if option is specified
bcgsc/abyss pull request #371
Opened 2021-05-25 13:06 UTC by jowong4

This pull request contains the features requested by Rene in order for it to be compatible with the new ntEdit + Sealer protocol. The idea is to seal softmasked regions using Sealer. To do this, we need to find flanks surrounding lower case iupac characters in addition to N/n. To turn this feature on, the user can specify "--lower".

2021-05-25 16:32 UTC, schutzekatze requested changes

2021-05-25 16:32 UTC, schutzekatze commented on Sealer/sealer.cc
> +	std::string gap = "Nn";
This can be a `const std::string`. You can initialize it with a ternary operator, like `const std::string gap(lower ? "..." : "...")`.

2021-05-25 16:32 UTC, schutzekatze commented on Sealer/sealer.cc
> +	auto case_flag = FastaReader::FOLD_CASE;
`const`

2021-05-25 16:32 UTC, schutzekatze commented on Sealer/sealer.cc
> +	bool lower)
Seeing as `lower` is part of `opt` namespace, passing a function parameter here might be adding unnecessary confusion. We can simply use `opt::lower` where needed.

2021-05-25 16:35 UTC, lcoombe commented on Sealer/sealer.cc
> +"      --lower                  seal sequences with atcgurykmswbdhvx chars\n"
```suggestion
"      --lower                  seal sequences with lower-case IUPAC characters\n"
```

2021-05-25 16:35 UTC, lcoombe commented on Sealer/sealer.cc
> +	/** Seal sequences with atcgurykmswbdhvx chars */
```suggestion
	/** Seal sequences with lower-case IUPAC characterss */
```

2021-09-20 15:50 UTC, lcoombe commented
@jowong4 - are we still planning on merging this feature to master branch?

2021-09-20 15:54 UTC, warrenlr commented
this is important for the protocol we are developing.
BF cross-compatibility is another important aspect of the protocol

2021-09-20 17:39 UTC, jowong4 commented
This PR was pending to be merged because Janet hasn't informed me if she needed any other features. If not, this PR is ready to be merged.

2021-09-21 20:26 UTC, merged